---
title: "Cycling and walking trends in the UK"
subtitle: "7th October 2021"
author: "Alex Hill"
output: ioslides_presentation
keep_md: true
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(plotly)
```
<style>
.title-slide hgroup h1 {
    margin-right: 100px;
}
article {
    margin-top: 10px !important;
}
.small {
    font-size: 20px;
}
</style>

## Cycling and walking in the UK

<p class="small">Hover cursor to interact with the graph (e.g. click and drag to zoom, hover over points to see values, click on series names to hide/show individual series)</p>

```{r}
cycling <- read.csv("data/cycling.csv")
fig <- plot_ly(cycling, x = ~year, y = ~once_per_month, name = "Once a month", type = 'scatter', mode = 'lines+markers')
fig %>%
  add_trace(y = ~once_per_week, name = 'Once a week', mode = 'lines+markers') %>%
  layout(title = "Percentage of adults in the UK who do any cycling or walking",
         xaxis = list(title = "Year"),
         yaxis = list(title = "%"))
```

## Acknowledgements

Data from https://www.gov.uk/government/collections/walking-and-cycling-statistics
